from generatorcore import makeentries
from generatorcore.refdata import RefData
from generatorcore.makeentries import make_entries, USER_OVERRIDABLE_ENTRIES


def test_user_overridable_entries():
    refdata = RefData.load()
    entries = make_entries(refdata, ags="DG000000", year=2035)
    missing = frozenset(USER_OVERRIDABLE_ENTRIES) - frozenset(entries.keys())
    assert (
        len(missing) == 0
    ), f"There are keys {missing} that we claim the user can override which are not generated by make_entries"
